2:
  feedback_template: |-
    Intro to Computer Systems :: Project 2 :: Combinational Chips

    Grading method: The implementation of some chips was described in the
    book, and some chips are simpler than others. The different weights
    assigned to the chips below reflect this variance.  If the chip passes
    all the tests specified in the supplied test script, it receives two
    thirds of its allotted points. The remaining third reflects our
    evaluation of the way the chip is built (we generally prefer
    implementations that use as few parts as possible, since additional
    parts can tax performance and be cost-ineffective).

    Chip                Working?            Well built?         Comments
  chips:
    -
      name: "HalfAdder"
      optimal_part_count: 2
      points:
        functionality: 6
        quality: 3
    -
      name: "FullAdder"
      optimal_part_count: 3
      points:
        functionality: 8
        quality: 4
    -
      name: "Add16"
      optimal_part_count: 16
      points:
        functionality: 8
        quality: 4
    -
      name: "Inc16"
      optimal_part_count: 1
      points:
        functionality: 10
        quality: 5
    -
      name: "ALU"
      optimal_part_count: 13
      points:
        functionality: 35
        quality: 17

3:
  feedback_template: |-
    // TODO

    Chip                Working?            Well built?         Comments
  chips:
    -
      name: "Bit"
      optimal_part_count: "unknown"
      points:
        functionality: 7
        quality: 3
    -
      name: "Register"
      optimal_part_count: "unknown"
      points:
        functionality: 7
        quality: 3
    -
      name: "RAM8"
      optimal_part_count: "unknown"
      points:
        functionality: 13
        quality: 6
    -
      name: "RAM64"
      optimal_part_count: "unknown"
      points:
        functionality: 13
        quality: 6
    -
      name: "RAM512"
      optimal_part_count: "unknown"
      points:
        functionality: 5
        quality: 3
    -
      name: "RAM4K"
      optimal_part_count: "unknown"
      points:
        functionality: 5
        quality: 3
    -
      name: "RAM16K"
      optimal_part_count: "unknown"
      points:
        functionality: 5
        quality: 3
    -
      name: "PC"
      optimal_part_count: "unknown"
      points:
        functionality: 12
        quality: 6

5:
  feedback_template: |-
    Intro to Computer Systems :: Project 5 :: Computer Architecture

    Grading method: The implementation of some chips was described in the
    book, and some chips are simpler than others. The different weights
    assigned to the chips below reflect this variance.  If the chip passes
    all the tests specified in the supplied test script, it receives two
    thirds of its allotted points. The remaining third reflects our
    evaluation of the way the chip is built (we generally prefer
    implementations that use as few parts as possible, since additional
    parts can tax performance and be cost-ineffective).

    Chip                Working?            Well built?         Comments
  additional_builtins:
    - "CPU"
    - "Memory"
  load_hack_programs: true
  chips:
    -
      name: "Memory"
      optimal_part_count: 5
      points:
        functionality: 17
        quality: 8
    -
      name: "CPU"
      optimal_part_count: 18
      points:
        functionality: 35
        quality: 18
    -
      name: "Computer"
      optimal_part_count: 3
      points:
        functionality: 15
        quality: 7
      tests:
        - "ComputerAdd"
        - "ComputerMax"
        - "ComputerRect"
