2:
  chips:
    -
      name: "HalfAdder"
      optimal_part_count: 2
      points:
        functionality: 6
        quality: 3
    -
      name: "FullAdder"
      optimal_part_count: 3
      points:
        functionality: 8
        quality: 4
    -
      name: "Add16"
      optimal_part_count: 16
      points:
        functionality: 8
        quality: 4
    -
      name: "Inc16"
      optimal_part_count: 1
      points:
        functionality: 10
        quality: 5
    -
      name: "ALU"
      optimal_part_count: 13
      points:
        functionality: 35
        quality: 17

5:
  additional_builtins:
    - "CPU"
    - "Memory"
  chips:
    -
      name: "Computer"
      optimal_part_count: 3
      points:
        functionality: 15
        quality: 7
      tests:
        - "ComputerAdd"
        - "ComputerMax"
        - "ComputerRect"
